//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Branchenverzeichnis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Company
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Company()
        {
            this.CompanyProduct = new HashSet<CompanyProduct>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Phonenumber { get; set; }
        public string Street { get; set; }
        public string PLZ { get; set; }
        public string Location { get; set; }
        public string CeoFirstName { get; set; }
        public string CeoLastName { get; set; }
        public Nullable<int> IndustryID { get; set; }
    
        public virtual Industry Industry { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CompanyProduct> CompanyProduct { get; set; }
    }
}
